language: go

go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get -v github.com/golang/lint/golint
  # hack for building on forks
  - repo=`basename $PWD`; src=`dirname $PWD`; dest="`dirname $src`/intel"
  - if [[ "$src" != "$dest" ]]; then mv "$src" "$dest"; cd ../../intel/$repo; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo; fi
script:
  - make format
  - make lint
  #- make
  #- make vet
  - make test
